### ISSUE TITLE
部署到Git Action（推荐）

### ISSUE THREAD

**Issue by xwwwb** [xwwwb/zzulidakadocs#7]
https://daka.xwwwb.com/#/ga 

 Description

**Comment by lixinyuepao** [comment]
晨检我这个没反应 归寝可以

**Comment by lixinyuepao** [comment]
我看在校打卡 下面 name 下面 有：这个： 还是不要这个：

**Comment by xwwwb** [comment]
> @lixinyuepao
> 我看在校打卡 下面 name 下面 有：这个： 还是不要这个：

不要冒号😂

**Comment by xwwwb** [comment]
> @lixinyuepao
> 晨检我这个没反应 归寝可以

github action的部署我们没有仔细检查过，等会我看看

**Comment by billionray** [comment]
> 我看在校打卡 下面 name 下面 有：这个： 还是不要这个：

您的问题是否已解决？
